# MoleSearch service configuration file
# Contains server configuration, MMExtractor configuration, SearchEngine configuration, etc.

# Server configuration
server:
  # Listening address
  host: "0.0.0.0"
  # Listening port
  port: 8000
  # Log level: DEBUG, INFO, WARNING, ERROR
  log_level: "INFO"
  # Development mode (enable code hot reload)
  dev_mode: false
  # Whether to enable access log
  access_log: true
  # Allowed cross-origin sources
  cors_origins: ["*"]
  # API documentation path
  docs_url: "/docs"
  redoc_url: "/redoc"

# File handler configuration
file_handler:
  # API key and credential configuration
  credentials:
    oss:
      access_key_id: "your_oss_access_key_id_here"
      access_key_secret: "your_oss_access_key_secret_here"
      endpoint: "oss-cn-hangzhou.aliyuncs.com"
      bucket_name: "mmretriever-audio"

# MMExtractor configuration
mmextractor:
  name: "MMExtractor"
  type: "extraction"
  enable: true
  
  # Plugin configuration
  plugins:
    # ASR (automatic speech recognition) plugin configuration
    ASRPluginParam:
      name: "asr"
      type: "speech_recognition"
      impl: "aliyun"
      param:
        # Aliyun OSS configuration (for temporary storage of audio files)
        oss_access_key_id: "your_oss_access_key_id_here"
        oss_access_key_secret: "your_oss_access_key_secret_here"
        oss_endpoint: "oss-cn-hangzhou.aliyuncs.com"
        oss_bucket_name: "mmretriever-audio"
        # ASR model configuration
        model: "paraformer-realtime-v2"
        api_key: "your_dashscope_api_key_here"
        audio_prefix: "audio_"
    
    # Text embedding plugin configuration
    TEmbedPluginParam:
      name: "text_embed"
      type: "text_embedding"
      impl: "qwen"
      param:
        api_key: "your_dashscope_api_key_here"
        model: "text-embedding-v4"
    
    # Image embedding plugin configuration
    IEmbedPluginParam:
      name: "image_embed"
      type: "image_embedding"
      impl: "qwen"
      param:
        api_key: "your_dashscope_api_key_here"
        model: "multimodal-embedding-v1"
    
    # Video embedding plugin configuration
    VEmbedPluginParam:
      name: "video_embed"
      type: "video_embedding"
      impl: "qwen"
      param:
        api_key: "your_dashscope_api_key_here"
        model: "multimodal-embedding-v1"
    
    # Vision language model plugin configuration
    VLMPluginParam:
      name: "vlm"
      type: "vision_language_model"
      impl: "qwen"
      param:
        api_key: "your_dashscope_api_key_here"
        model: "qwen-vl-max-latest"
        prompt_path: "tests/qwen_vlm_prompt.txt"

# Search engine configuration
search_engine:
  type: "elasticsearch"
  config:
    # Elasticsearch connection configuration
    host: "localhost"
    port: 9200
    # Protocol: http or https
    scheme: "http"
    # Index name
    index: "mmretriever"
    # Authentication configuration (optional)
    username: ""
    password: ""
    # Connection timeout (seconds)
    timeout: 30
    # Maximum number of retries
    max_retries: 3
    # Vector dimension configuration
    vector_dimensions:
      text_embedding: 1536
      image_embedding: 1536
      video_embedding: 1536
    # Batch insert configuration
    batch_size: 100
    # Index refresh policy
    refresh_policy: "wait_for"

# Configuration validation
validation:
  # Verify required configuration items
  required_fields:
    - "file_handler.credentials.oss.access_key_id"
    - "file_handler.credentials.oss.access_key_secret"
  
  # Verify configuration item format
  format_validation:
    dashscope_api_key_min_length: 20
    oss_endpoint_pattern: "^oss-.*\\.aliyuncs\\.com$"
    token_min_length: 10

# Performance configuration
performance:
  # Concurrent processing configuration
  max_concurrent_requests: 10
  # Request timeout (seconds)
  request_timeout: 300
  # Memory configuration
  max_memory_mb: 2048
  # Cache configuration
  cache:
    enable: true
    ttl: 3600  # Cache TTL (seconds)
    max_size: 1000  # Maximum cache entries

# Security configuration
security:
  # User authentication configuration
  user_auth:
    enable: true
    users:
      - username: "admin"
        password: "admin123"
        role: "admin"
      - username: "user"
        password: "user123"
        role: "user"
    # Redis configuration for token storage
    redis:
      host: "localhost"
      port: 6379
      db: 0
      password: null
      decode_responses: true
  # API key configuration (optional)
  api_key_required: false
  api_key_header: "X-API-Key"
  # Rate limiting configuration
  rate_limit:
    enable: false
    requests_per_minute: 100
    burst_size: 20

# Monitoring configuration
monitoring:
  # Health check configuration
  health_check:
    endpoint: "/health"
    interval: 30  # Check interval (seconds)
  
  # Metrics collection configuration
  metrics:
    enable: true
    endpoint: "/metrics"
    collect_system_metrics: true
    collect_app_metrics: true

# Logging configuration
logging:
  # Log level
  level: "INFO"
  # Log format: json or text
  format: "json"
  # Log output location
  output: "stdout"
  # Log file configuration (when output contains file)
  file:
    path: "logs/mmretriever.log"
    max_size: "100MB"
    backup_count: 5
    rotation: "daily"
  # Request log configuration
  access_log:
    enable: true
    format: "%(h)s %(l)s %(u)s %(t)s \"%(r)s\" %(s)s %(b)s \"%(f)s\" \"%(a)s\""

# Data processing configuration
data_processing:
  # File upload configuration
  upload:
    max_file_size: "100MB"
    allowed_extensions: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".mp4", ".avi", ".mov", ".wmv", ".flv", ".webm", ".txt", ".pdf", ".doc", ".docx"]
    temp_dir: "/tmp/mmretriever"
  
  # Image processing configuration
  image:
    max_width: 2048
    max_height: 2048
    quality: 85
    format: "JPEG"
  
  # Video processing configuration
  video:
    max_duration: 600  # Maximum video duration (seconds)
    max_size: "500MB"
    extract_frames: true
    frame_interval: 1  # Frame extraction interval (seconds)

# Storage configuration
storage:
  # Temporary file storage
  temp:
    path: "/tmp/mmretriever"
    cleanup_interval: 3600  # Cleanup interval (seconds)
    max_age: 86400  # Maximum file survival time (seconds)
  
  # Persistent storage (optional)
  persistent:
    enable: false
    path: "/data/mmretriever"
    backup_interval: 86400  # Backup interval (seconds)